name: Build and publish windmill-gdal docker image

on:
  push:
    paths:
      - workers/gdal/**

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

    - uses: actions/checkout@master

    - name: Get version tag
      id: get_tag
      run: |
        if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
          echo "tag=${GITHUB_REF:10}" >>$GITHUB_OUTPUT
        else
          echo "tag=latest" >>$GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and publish docker image
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: sourcepole/windmill-gdal
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tags: ${{ steps.get_tag.outputs.tag }}
        workdir: workers/gdal/
