name: Build and publish windmill-osm docker image

on:
  push:
    paths:
      - workers/osm/**

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

    - uses: actions/checkout@master

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and publish latest docker image
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: sourcepole/windmill-osm
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tags: latest
        workdir: workers/osm/

    - name: Check whether version file has changed
      uses: dorny/paths-filter@v2
      id: paths_filter
      with:
        base: ${{ github.ref }}
        filters: |
          osm_version:
            - 'workers/osm/version.txt'

    - name: Get version tag from file
      id: get_tag
      if: steps.paths_filter.outputs.osm_version == 'true'
      run: |
        version_tag=$(cat workers/osm/version.txt || echo 'latest')
        echo "Read version file: $version_tag"
        echo "tag=$version_tag" >>$GITHUB_OUTPUT

    - name: Build and publish tagged docker image
      uses: elgohr/Publish-Docker-Github-Action@v4
      if: steps.paths_filter.outputs.osm_version == 'true'
      with:
        name: sourcepole/windmill-osm
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tags: ${{ steps.get_tag.outputs.tag }}
        workdir: workers/osm/
